#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Apr 11 10:57:18 2022
total surface mass density vs r    HOMENTROPIC
@author: kedarkulkarni
"""

import matplotlib.pyplot as plt
import numpy as np


# make data
x = np.linspace(0.4, 1.6, 128)
S i g = 1+((0.109)∗np.exp((−(x−1)∗∗2/0.05)))

# plot
fig, ax = plt.subplots()

ax.plot(x, sig, linewidth=2.0)

ax.set(xlim=(0, 2), xticks=np.arange(0,2, 0.2) )
plt.grid()
plt.title("Tptal surface mass density vs r homentropic")
plt.ylabel("total surface mass density")
plt.xlabel("r")


plt.show()

